# Generated by Django 6.0.5 on 2026-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_alter_reservation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="theme",
            field=models.ManyToManyField(
                related_name="shows", to="planetarium.showtheme"
            ),
        ),
    ]
