# Generated by Django 6.0.5 on 2026-05-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_alter_astronomyshow_theme"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="showsession",
            unique_together={("astronomy_show", "planetarium_dome", "show_time")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "row", "seat")},
        ),
    ]
