# Generated by Django 6.0.5 on 2026-05-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0005_alter_showsession_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="theme",
            new_name="themes",
        ),
    ]
