# Generated by Django 6.0.5 on 2026-05-16 08:09

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0006_rename_theme_astronomyshow_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="poster_image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.movie_image_file_path
            ),
        ),
    ]
