# Generated by Django 6.0.5 on 2026-05-16 09:03

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
